from django.urls import path
from . import views
from . import api_endpoints
from . import api_views
from . import drf_views

urlpatterns = [
    path('', views.menu, name='menu'),
    path('equipos/', views.equipos, name='equipos'),
    path('favoritos/select/', views.select_favorite_teams, name='select_favorite_teams'),
    path('favoritos/toggle/', views.toggle_favorite_team, name='toggle_favorite_team'),
    path('mi-plantilla/', views.mi_plantilla, name='mi_plantilla'),
    path('clasificacion/', views.clasificacion, name='clasificacion'),
    path('equipo/<str:equipo_nombre>/', views.equipo, name='equipo'),
    path('equipo/<str:equipo_nombre>/<str:temporada>/', views.equipo, name='equipo_temporada'),
    path('jugador/', views.jugador, name='jugador'),
    path('jugador/<int:jugador_id>/', views.jugador, name='jugador_detail'),
    path('jugador/<int:jugador_id>/<str:temporada>/', views.jugador, name='jugador_temporada'),
    path('amigos/', views.amigos, name='amigos'),
    path('login/', views.login_register, name='login_register'),
    path('login/submit/', views.login_view, name='login'),
    path('register/submit/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil/', views.perfil_usuario, name='perfil'),
    path('perfil/upload-photo/', views.upload_profile_photo, name='upload_profile_photo'),
    path('perfil/update/', views.update_profile, name='update_profile'),
    path('perfil/update-status/', views.update_user_status, name='update_user_status'),
    path('perfil/delete-favorite/<int:fav_id>/', views.delete_favorite_team, name='delete_favorite_team'),
    path('mi-plantilla/guardar/', views.guardar_plantilla, name='guardar_plantilla'),
    path('mi-plantilla/listar/', views.listar_plantillas, name='listar_plantillas'),
    path('mi-plantilla/<int:plantilla_id>/', views.obtener_plantilla, name='obtener_plantilla'),
    path('mi-plantilla/<int:plantilla_id>/eliminar/', views.eliminar_plantilla, name='eliminar_plantilla'),
    path('mi-plantilla/<int:plantilla_id>/renombrar/', views.renombrar_plantilla, name='renombrar_plantilla'),
    path('terms-conditions/', views.terms_conditions, name='terms_conditions'),
    # API Endpoints (existing)
    path('api/radar/<int:jugador_id>/<str:temporada>/', api_endpoints.api_radar_jugador, name='api_radar_jugador'),
    path('api/buscar/', api_endpoints.api_buscar, name='api_buscar'),
    path('api/favoritos/toggle/', api_endpoints.api_toggle_favorito, name='api_toggle_favorito'),
    path('api/predecir-portero/', views.predecir_portero_api, name='predecir_portero_api'),
    path('api/predecir-jugador/', views.predecir_jugador_api, name='predecir_jugador_api'),
    path('api/explicar-prediccion/', views.explicar_prediccion_portero_api, name='explicar_prediccion_portero_api'),
    path('api/cambiar-jornada/', views.cambiar_jornada_api, name='cambiar_jornada_api'),

    # ── React Frontend JSON API ──────────────────────────────────────────────
    path('api/me/', api_views.api_me, name='api_me'),
    path('api/auth/login/', api_views.api_login, name='api_auth_login'),
    path('api/auth/logout/', api_views.api_logout, name='api_auth_logout'),
    path('api/auth/register/', api_views.api_register, name='api_auth_register'),
    path('api/menu/', api_views.api_menu, name='api_menu'),
    path('api/clasificacion/', api_views.api_clasificacion, name='api_clasificacion'),
    path('api/top-jugadores-por-posicion/', api_views.api_top_jugadores_por_posicion, name='api_top_jugadores_por_posicion'),
    path('api/equipos/', api_views.api_equipos, name='api_equipos'),
    path('api/equipo/<str:equipo_nombre>/', api_views.api_equipo, name='api_equipo'),
    path('api/jugador/<int:jugador_id>/', api_views.api_jugador, name='api_jugador'),
    path('api/perfil/', api_views.api_perfil, name='api_perfil'),
    path('api/perfil/update/', api_views.api_update_perfil, name='api_update_perfil'),
    path('api/perfil/status/', api_views.api_update_status, name='api_update_status'),
    path('api/perfil/foto/', api_views.api_upload_photo, name='api_upload_photo'),
    path('api/favoritos/', api_views.api_favoritos, name='api_favoritos'),
    path('api/favoritos/toggle-v2/', api_views.api_toggle_favorito_v2, name='api_toggle_favorito_v2'),
    path('api/favoritos/seleccionar/', api_views.api_select_favorites, name='api_select_favorites'),
    path('api/favoritos/<int:fav_id>/', api_views.api_delete_favorito, name='api_delete_favorito'),
    path('api/amigos/', api_views.api_amigos, name='api_amigos'),
    path('api/amigos/solicitud/', api_views.api_enviar_solicitud, name='api_enviar_solicitud'),
    path('api/amigos/aceptar/<int:solicitud_id>/', api_views.api_aceptar_solicitud, name='api_aceptar_solicitud'),
    path('api/amigos/rechazar/<int:solicitud_id>/', api_views.api_rechazar_solicitud, name='api_rechazar_solicitud'),
    path('api/amigos/eliminar/<int:user_id>/', api_views.api_eliminar_amigo, name='api_eliminar_amigo'),
    path('api/amigos/<int:user_id>/plantillas/', api_views.api_plantillas_amigo, name='api_plantillas_amigo'),
    path('api/mi-plantilla/', api_views.api_mi_plantilla, name='api_mi_plantilla'),
    path('api/mi-plantilla/jugadores/', api_views.api_mi_plantilla_jugadores, name='api_mi_plantilla_jugadores'),
    path('api/notificaciones/', api_views.api_notificaciones, name='api_notificaciones'),
    path('api/notificaciones/leer-todas/', api_views.api_marcar_todas_leidas, name='api_marcar_todas_leidas'),
    path('api/notificaciones/<int:notif_id>/leer/', api_views.api_marcar_notificacion_leida, name='api_marcar_notificacion_leida'),
    path('api/notificaciones/<int:notif_id>/borrar/', api_views.api_borrar_notificacion, name='api_borrar_notificacion'),
    path('api/notificaciones/borrar-todas/', api_views.api_borrar_todas_notificaciones, name='api_borrar_todas_notificaciones'),
    path('api/perfil/preferencias-notificaciones/', api_views.api_update_preferencias_notificaciones, name='api_update_preferencias_notificaciones'),
    path('api/plantilla/<int:plantilla_id>/privacidad/', api_views.api_toggle_privacidad_plantilla, name='api_toggle_privacidad_plantilla'),
    path('api/plantilla/<int:plantilla_id>/predeterminada/', api_views.api_set_plantilla_predeterminada, name='api_set_plantilla_predeterminada'),
    path('api/plantillas/privacidad/', api_views.api_mis_plantillas_privacidad, name='api_mis_plantillas_privacidad'),

    # ── REST API v2 (DRF) ────────────────────────────────────────────────────
    # Jugadores
    path('api/v2/jugadores/', drf_views.JugadorListView.as_view(), name='v2_jugadores'),
    path('api/v2/jugadores/<int:jugador_id>/', drf_views.JugadorDetailView.as_view(), name='v2_jugador_detail'),
    path('api/v2/jugadores/<int:jugador_id>/predicciones/', drf_views.JugadorPrediccionesView.as_view(), name='v2_jugador_predicciones'),
    # Equipos
    path('api/v2/equipos/', drf_views.EquipoListView.as_view(), name='v2_equipos'),
    path('api/v2/equipos/<str:equipo_nombre>/', drf_views.EquipoDetailView.as_view(), name='v2_equipo_detail'),
    # Otros recursos
    path('api/v2/clasificacion/', drf_views.clasificacion_view, name='v2_clasificacion'),
    path('api/v2/jornadas/', drf_views.jornadas_view, name='v2_jornadas'),
    # Predicciones (escritura autenticada)
    path('api/v2/predicciones/', drf_views.PrediccionCreateView.as_view(), name='v2_predicciones'),
]
