# Generated by Django 5.2.11 on 2026-02-05 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estadio', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jornada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['temporada', 'numero_jornada'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('posicion', models.CharField(choices=[('Portero', 'Portero'), ('Defensa', 'Defensa'), ('Centrocampista', 'Centrocampista'), ('Delantero', 'Delantero')], max_length=30)),
                ('nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateTimeField(blank=True, null=True)),
                ('goles_local', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_visitante', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('JUGADO', 'Jugado'), ('PENDIENTE', 'Pendiente'), ('APLAZADO', 'Aplazado')], default='PENDIENTE', max_length=20)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='main.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='main.equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='main.jornada')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha_partido'],
            },
        ),
        migrations.AddField(
            model_name='jornada',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='main.temporada'),
        ),
        migrations.CreateModel(
            name='HistorialEquiposJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(50)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_equipos', to='main.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temporada')),
            ],
            options={
                'verbose_name': 'Historial Equipos Jugador',
                'verbose_name_plural': 'Historiales Equipos Jugadores',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasPartidoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_jugados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('goles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('asistencias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('disparos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('disparos_a_puerta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pases_completados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pases_totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('regates', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('despejes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('faltas_cometidas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarjetas_amarillas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('tarjetas_rojas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('recuperaciones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('intercepciones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('entradas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duelos_ganados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duelos_totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('calificacion_decimal', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('en_alineacion', models.BooleanField(default=True)),
                ('fue_suplente', models.BooleanField(default=False)),
                ('minuto_salida', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('minuto_entrada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gol_en_propia_puerta', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_partidos', to='main.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_jugadores', to='main.partido')),
            ],
            options={
                'verbose_name': 'Estadísticas Partido Jugador',
                'verbose_name_plural': 'Estadísticas Partidos Jugadores',
                'ordering': ['-partido__fecha_partido'],
                'unique_together': {('partido', 'jugador')},
            },
        ),
        migrations.CreateModel(
            name='RendimientoHistoricoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('partidos_como_titular', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minutos_totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_temporada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('asistencias_temporada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarjetas_amarillas_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarjetas_rojas_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('promedio_calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pases_completados_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_en_propia_puerta_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimiento_historico', to='main.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temporada')),
            ],
            options={
                'verbose_name': 'Rendimiento Histórico Jugador',
                'verbose_name_plural': 'Rendimientos Históricos Jugadores',
                'ordering': ['-temporada', '-goles_temporada'],
                'unique_together': {('jugador', 'temporada')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='jornada',
            unique_together={('temporada', 'numero_jornada')},
        ),
        migrations.CreateModel(
            name='EquipoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temporada')),
            ],
            options={
                'verbose_name': 'Equipo Temporada',
                'verbose_name_plural': 'Equipos Temporada',
                'ordering': ['temporada', 'equipo'],
                'unique_together': {('equipo', 'temporada')},
            },
        ),
        migrations.CreateModel(
            name='ClasificacionJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('puntos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_favor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_contra', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('partidos_empatados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('partidos_perdidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('racha_reciente', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jornada')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temporada')),
            ],
            options={
                'verbose_name': 'Clasificación Jornada',
                'verbose_name_plural': 'Clasificaciones Jornada',
                'ordering': ['temporada', 'jornada', 'posicion'],
                'unique_together': {('temporada', 'jornada', 'equipo')},
            },
        ),
    ]
