# Generated by Django 5.2.11 on 2026-02-06 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='asistencias',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='calificacion_decimal',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='disparos',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='disparos_a_puerta',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='duelos_totales',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='en_alineacion',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='faltas_cometidas',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='fue_suplente',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='gol_en_propia_puerta',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='goles',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='intercepciones',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='minuto_entrada',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='minuto_salida',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='minutos_jugados',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='pases_completados',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='recuperaciones',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='tarjetas_amarillas',
        ),
        migrations.RemoveField(
            model_name='estadisticaspartidojugador',
            name='tarjetas_rojas',
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='amarillas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='asist_partido',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='bloqueo_pase',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='bloqueo_tiros',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='bloqueos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='conducciones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='conducciones_progresivas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='distancia_conduccion',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='duelos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='duelos_aereos_ganados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='duelos_aereos_ganados_pct',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='duelos_aereos_perdidos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='duelos_perdidos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='gol_partido',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='goles_en_contra',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='metros_avanzados_conduccion',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='min_partido',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='pases_completados_pct',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='porcentaje_paradas',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='psxg',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='puntos_fantasy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='regates_completados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='regates_fallidos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='rojas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='tiro_fallado_partido',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='tiro_puerta_partido',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='tiros',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='titular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='xag',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='xg_partido',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
