# Generated by Django 5.2.11 on 2026-02-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_estadisticaspartidojugador_asistencias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialequiposjugador',
            options={'ordering': ['temporada', 'equipo'], 'verbose_name': 'Historial Equipos Jugador', 'verbose_name_plural': 'Historiales Equipos Jugadores'},
        ),
        migrations.AlterUniqueTogether(
            name='historialequiposjugador',
            unique_together={('jugador', 'equipo', 'temporada')},
        ),
        migrations.RemoveField(
            model_name='rendimientohistoricojugador',
            name='promedio_calificacion',
        ),
        migrations.RemoveField(
            model_name='historialequiposjugador',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='historialequiposjugador',
            name='fecha_inicio',
        ),
    ]
