# Generated by Django 5.2.11 on 2026-02-06 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_historialequiposjugador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialequiposjugador',
            name='dorsal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
