# Generated by Django 5.2.11 on 2026-02-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_historialequiposjugador_dorsal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialequiposjugador',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
