# Generated by Django 5.2.11 on 2026-02-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_historialequiposjugador_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialequiposjugador',
            name='nacionalidad',
        ),
    ]
