# Generated by Django 6.0.1 on 2026-02-07 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_historialequiposjugador_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoJugadorTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(50)])),
                ('partidos_jugados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_temporada', to='main.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_temporada', to='main.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temporada')),
            ],
            options={
                'verbose_name': 'Equipo Jugador Temporada',
                'verbose_name_plural': 'Equipos Jugadores Temporadas',
                'ordering': ['temporada', 'equipo', 'jugador__apellido'],
                'unique_together': {('equipo', 'jugador', 'temporada')},
            },
        ),
    ]
