# Generated by Django 5.2.11 on 2026-02-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_equipojugadortemporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipojugadortemporada',
            name='posicion_transfermarkt',
            field=models.CharField(choices=[('Portero', 'Portero'), ('Defensa', 'Defensa'), ('Centrocampista', 'Centrocampista'), ('Delantero', 'Delantero')], default='Centrocampista', max_length=30),
        ),
        migrations.AddField(
            model_name='historialequiposjugador',
            name='posicion_transfermarkt',
            field=models.CharField(choices=[('Portero', 'Portero'), ('Defensa', 'Defensa'), ('Centrocampista', 'Centrocampista'), ('Delantero', 'Delantero')], default='Centrocampista', max_length=30),
        ),
    ]
