# Generated by Django 5.2.11 on 2026-02-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_equipojugadortemporada_posicion_transfermarkt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipojugadortemporada',
            name='posicion_transfermarkt',
        ),
    ]
