# Generated by Django 5.2.11 on 2026-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_equipojugadortemporada_posicion_transfermarkt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipojugadortemporada',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='historialequiposjugador',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='posicion',
        ),
        migrations.AlterField(
            model_name='historialequiposjugador',
            name='posicion_transfermarkt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
