# Generated by Django 6.0.1 on 2026-02-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_equipojugadortemporada_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='posicion',
            field=models.CharField(blank=True, choices=[('Portero', 'Portero'), ('Defensa', 'Defensa'), ('Centrocampista', 'Centrocampista'), ('Delantero', 'Delantero')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialequiposjugador',
            name='posicion_transfermarkt',
            field=models.CharField(blank=True, choices=[('Portero', 'Portero'), ('Defensa', 'Defensa'), ('Centrocampista', 'Centrocampista'), ('Delantero', 'Delantero')], max_length=30, null=True),
        ),
    ]
