# Generated by Django 6.0.1 on 2026-02-08 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_estadisticaspartidojugador_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipojugadortemporada',
            name='edad',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
