# Generated by Django 6.0.1 on 2026-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_equipojugadortemporada_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estadio',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
