# Generated by Django 6.0.1 on 2026-02-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipojugadortemporada',
            name='percentiles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='equipojugadortemporada',
            name='posicion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
