# Generated by Django 6.0.1 on 2026-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userprofile_equipofavorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('active', 'Activo'), ('away', 'Ausente'), ('dnd', 'No molestar')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
