# Generated by Django 6.0.1 on 2026-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userprofile_estado_userprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plantilla_guardada',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
