# Generated by Django 5.1.4 on 2026-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_add_amistad_notificacion_privacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='predeterminada',
            field=models.BooleanField(default=False),
        ),
    ]
