# Generated by Django 5.1.4 on 2026-03-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_plantilla_predeterminada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediccion', models.FloatField(help_text='Puntos fantasy predichos')),
                ('modelo', models.CharField(choices=[('xgb', 'XGBoost'), ('rf', 'Random Forest'), ('lgbm', 'LightGBM')], default='xgb', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_jugadores', to='main.jornada')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='main.jugador')),
            ],
            options={
                'verbose_name': 'Predicción Jugador',
                'verbose_name_plural': 'Predicciones Jugadores',
                'ordering': ['-jornada__temporada__nombre', 'jornada__numero_jornada'],
                'unique_together': {('jugador', 'jornada', 'modelo')},
            },
        ),
    ]
