# Generated by Django 5.1.4 on 2026-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_historial_and_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jornada_pref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
