# Generated by Django 5.1.4 on 2026-03-04 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_userprofile_jornada_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='faltas_cometidas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='faltas_recibidas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='lanzadores_corners',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='lanzadores_penalties',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estadisticaspartidojugador',
            name='pases_clave',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
