# Generated by Django 5.1.4 on 2026-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_estadisticaspartidojugador_faltas_cometidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionjugador',
            name='modelo',
            field=models.CharField(choices=[('xgb', 'XGBoost'), ('rf', 'Random Forest'), ('lgbm', 'LightGBM'), ('ridge', 'Ridge Regression')], default='rf', max_length=10),
        ),
    ]
