# Generated by Django 5.1.4 on 2026-03-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_ridge_to_prediccion_modelos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionjugador',
            name='modelo',
            field=models.CharField(choices=[('xgb', 'XGBoost'), ('rf', 'Random Forest'), ('lgbm', 'LightGBM'), ('ridge', 'Ridge Regression'), ('baseline', 'Baseline (Media)')], default='rf', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
