# Generated by Django 5.1.4 on 2026-03-07 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_fix_rendimiento_unique_jugador_temporada_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Generada'), ('failed', 'Error')], default='pending', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('intentos', models.IntegerField(default=0)),
                ('motivo_error', models.TextField(blank=True, default='')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_prediccion', to='main.jornada')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_prediccion', to='main.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_prediccion', to='main.temporada')),
            ],
            options={
                'verbose_name': 'Pedido Predicción',
                'verbose_name_plural': 'Pedidos Predicción',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado', 'temporada'], name='pred_estado_temp_idx'), models.Index(fields=['jugador', 'estado'], name='pred_jugador_estado_idx')],
                'unique_together': {('jugador', 'jornada', 'temporada')},
            },
        ),
    ]
