# Generated by Django 5.1.4 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_pedidoprediccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='frontend-web/userprofilefotos/'),
        ),
    ]
