name: Supabase Keep Alive API

on:
  schedule:
    # Se ejecuta a las 00:00 cada 3 días
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Esto permite que lo pruebes manualmente ahora

jobs:
  ping_api:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Supabase
        run: |
          # Hacemos la petición a tu URL de proyecto
          curl -i -X GET "https://cmkwgfkwvvtpdlfvcheb.supabase.co/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
